apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-training
  region: us-east-1
  version: "1.25"
managedNodeGroups:
  - name: small-nodes
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 20
    privateNetworking: false # Public subnet for the worker nodes
    ssh:
      allow: true
iam:
  withOIDC: true
